### ISSUE TITLE
Valygar's Suna aftertalk needs closing variable

### ISSUE THREAD

**Issue by Gitjas** [AngelGryph/UnfinishedBusiness#5]
Hi AngelGryph,

the Suna Seni follow-up dialogue in u!suna.d needs a closing of the variable "u!SunaDies", or it triggers every time Valygar is spoken to after the Spellhold incident (and overwriting the PID of the Corthala Romantique mod):

IF ~Global("u!SunaDies","GLOBAL",2)~ THEN BEGIN ValSunaSHBye1
  SAY @316
  IF ~~ THEN GOTO ValSunaDead
END

should be:

IF ~Global("u!SunaDies","GLOBAL",2)~ THEN BEGIN ValSunaSHBye1
  SAY @316
  IF ~~ THEN DO ~SetGlobal("u!SunaDies","GLOBAL",3)~ 
GOTO ValSunaDead
END

**Comment by Gitjas** [comment]
Not sure why things in tildas gets written as crossed out, here is another try:
`IF ~Global("u!SunaDies","GLOBAL",2)~ THEN BEGIN ValSunaSHBye1
SAY @316
IF ~~ THEN GOTO ValSunaDead
END

should be

IF ~Global("u!SunaDies","GLOBAL",2)~ THEN BEGIN ValSunaSHBye1
SAY @316
IF ~~ THEN DO ~SetGlobal("u!SunaDies","GLOBAL",3)~
GOTO ValSunaDead
END`

**Comment by Gitjas** [comment]
OK, I give up - what is the "insert code" tag for if it does the same stupid format changes?

-The crossed out Globals should be in tildas and not crossed out. I guess you get the idea.

**Comment by i30817** [comment]
> OK, I give up - what is the "insert code" tag for if it does the same stupid format changes?
> 
> -The crossed out Globals should be in tildas and not crossed out. I guess you get the idea.

you should use the 'insert code' button after selecting the part of the text that is code to prevent formatting problems like this.

**Comment by Gitjas** [comment]
I tried:
```
IF ~Global("u!SunaDies","GLOBAL",2)~ THEN BEGIN ValSunaSHBye1
SAY @316
IF ~~ THEN DO ~SetGlobal("u!SunaDies","GLOBAL",3)~
GOTO ValSunaDead
END
```

**Comment by Gitjas** [comment]
Ha! this time it worked, thanks. 
The last comment shows the fix.
